import os

SECRET_KEY = os.environ.get('SECRET_KEY')

DB_USERNAME = os.environ.get('DB_USERNAME')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DB_HOST = os.environ.get('DB_HOST')
DB_NAME = os.environ.get('DB_NAME')
DB_URI = f'postgresql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}'

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

PAGINATION_PAGE_SIZE = os.environ.get('PAGINATION_PAGE_SIZE')
PAGINATION_PAGE_ARGUMENT_NAME = os.environ.get('PAGINATION_PAGE_ARGUMENT_NAME')
